services:
  redis:
    image: redis:7
    container_name: pokedot-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
  postgres:
    image: postgres:15
    container_name: pokedot-pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pokedot
      POSTGRES_PASSWORD: pokedotpassword
      POSTGRES_DB: pokedot_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pokedot"]
      interval: 30s
      timeout: 5s
      retries: 5
volumes:
  redis-data:
  postgres-data:
